(defpackage #:hominy/treec
  (:use #:cl)
  (:shadow #:compile #:tailp)
  (:local-nicknames (#:i #:hominy/interpreter)
                    (#:syms #:hominy/interpreter/syms)
                    (#:baselib #:hominy/baselib)
                    (#:cenv #:hominy/cenv)
                    (#:info #:hominy/info)
                    (#:o #:hominy/vm/ops)
                    (#:vm #:hominy/vm)
                    (#:class #:hominy/vm/class)
                    (#:asm #:hominy/vm/asm))
  (:export #:compile #:module))
